In [3]:
import re
import random
import numpy as np
from string import ascii_uppercase


In [4]:
#INITIALIZATION OF GAME
#Defined size of board (rows m , colums n)
m = 10; n = 10

#Defined length of ships
ships_size={"carrier":5,
"battleship":4,
"cruiser":3,
"submarine":3,
"destroyer": 2}

#Defined code of ships
ships_code={"carrier":1,
"battleship":2,
"cruiser":3,
"submarine":4,
"destroyer": 5}
#Maximum number of guesses
max_guess = 60


In [16]:
def create_board(m=10,n=10):
    """ returns an numpy array of size m*n filled with Zero values"""
    return np.zeros((m,n))
def position_ships(ships_code,ships_size, m=10,n=10):
    """
    Returns a list of positions values in the form of letter and number 
    based on the ship sizes in dictionary ships_size
    """
    ships_pos_dic = {} #Dictionary holding position for each list

    pc_board = create_board()
    for iship,isize  in ships_size.items():
        ships_pos_dic[iship] = []
        flagOkposition=True
        while flagOkposition:
            positionx = random.choice(range(0,n))
            positiony = random.choice(range(0,m))
            angleship = random.choice(("v","h"))
            print(f"first poistion of ship x{positionx}, y{positiony} and lays {angleship}")
            if angleship == "v":
                if (positiony + isize) >=m :
                    print("try another starting position")
                else:
                    print(positiony + isize)
                    pc_board[positiony:(positiony+isize),positionx] = ships_code[iship]
                    for ipos in range(positiony,positiony+isize):
                        list_ship_pos = ships_pos_dic[iship] 
                        list_ship_pos.append(ascii_uppercase[ipos]+str(positionx+1))
                    flagOkposition = False
            else:
                if (positionx + isize) >=n or positiony >=m:
                    print("try another starting position")
                else:
                    print(positionx+isize)
                    pc_board[positiony,positionx:(positionx+isize)] = ships_code[iship]
                    for ipos in range(positionx,positionx+isize):
                        list_ship_pos = ships_pos_dic[iship] 
                        list_ship_pos.append(ascii_uppercase[positiony+1]+str(ipos+1))
                    flagOkposition = False
    print(pc_board)
    print(ships_pos_dic)
    list_final_pos = []
    for positionlist in ships_pos_dic.values():
        list_final_pos.extend(positionlist)
    return pc_board,ships_pos_dic, list_final_pos
# Function with a starting number of guesses (ex: 65):
# For each guess: decrementing by 1 at each guesses.
# While not all ships sunk and number of guesses >= 1, ask this

# This function checks that the case entered is correct
def guess():
    # Asking player to enter a letter 
    letter_lin = str(input("Enter a line between A and J: "))
    letter_lin = letter_lin.upper()
    
    # Checking if letter is within range of the board with while loop and using a boolean and not stopping until condition is met
    pattern = "[ABCDEFGHIJ]"
    
    while (bool(re.search(pattern, letter_lin)) is False) :
        letter_lin = str(input("An incorrect character or out of range letter was entered.\n Please enter a column between A and J: "))
        letter_lin = letter_lin.upper()

    # Checking if multiple characters are not entered and not stopping until condition is met
    while len(letter_lin) != 1:
        letter_lin = str(input("You entered more than 1 character.\n Please enter a column between A and J: "))
        letter_lin = letter_lin.upper()

    # Asking player to enter a letter 
    column_num = int(input("Enter a number between 1 and 10: "))
    
    # Checking if number is within range and keep asking until in range
    while not 1<=column_num<=10 :
        column_num = int(input("An incorrect character or out of range letter was entered.\n Please enter a column between 1 and 10: "))    

    # Transforming the number into string
    str_column_num = str(column_num)
    
    # Joining the strings to have the identity of the case (ex: B7)
    case = letter_lin+str_column_num


In [17]:
pc_board,ships_pos_dic,list_final_pos = position_ships(ships_code, ships_size)

first poistion of ship x1, y2 and lays v
7
first poistion of ship x5, y4 and lays h
9
first poistion of ship x8, y4 and lays v
7
first poistion of ship x3, y6 and lays v
9
first poistion of ship x9, y0 and lays h
try another starting position
first poistion of ship x4, y2 and lays h
6
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 5. 5. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 2. 2. 2. 3. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 1. 0. 4. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'carrier': ['C2', 'D2', 'E2', 'F2', 'G2'], 'battleship': ['F6', 'F7', 'F8', 'F9'], 'cruiser': ['E9', 'F9', 'G9'], 'submarine': ['G4', 'H4', 'I4'], 'destroyer': ['D5', 'D6']}


In [24]:
import matplotlib.pyplot as plt

def transform_case(case):
    y = ord(case[0].lower()) - 96 #to ascii 
    x = int(case[1])
    return y,x #For numpy array

def visu_board(already_guessed, list_hits, m, n):
    """
    Touch = X 
    MISSED = o

    dic values :
        
    """
    game_board = create_board()
    for case in already_guessed:
        iy, ix = transform_case(case)
        if case in list_hits:
            game_board[iy,ix] = 3
        else:
            game_board[iy,ix] = 2
    img = plt.imshow(game_board)
    return img
    


In [15]:

case = input("Please insert letter and number")
already_guessed=[]
list_hits = []
if case in list_final_pos:
    print("TOUCHED")
    list_hits.append(case)
    shipsunk = 0
    for shipname,ship_listi in ships_pos_dic.items():
        if case in ship_listi:
            ship_listi.remove(case)
            if len(ship_listi)==0:
                print("SUNK")
                shipsunk+=1
        if shipsunk == len(ships_pos_dic.keys()):
            print("YOU WON")
            #break
else:
    print ("MISSED")
    
#guess -=1
already_guessed.append(case)

MISSED


In [23]:
number = ord("A".lower()) - 96
print(number)


1
