In [16]:
import re
import random
import numpy as np
from string import ascii_uppercase


In [7]:
#INITIALIZATION OF GAME
#Defined size of board (rows m , colums n)
m = 10; n = 10

#Defined length of ships
ships_size={"carrier":5,
"battleship":4,
"cruiser":3,
"submarine":3,
"destroyer": 2}

#Defined code of ships
ships_code={"carrier":1,
"battleship":2,
"cruiser":3,
"submarine":4,
"destroyer": 5}
#Maximum number of guesses
max_guess = 60


In [53]:
def create_board(m=10,n=10):
    """ returns an numpy array of size m*n filled with Zero values"""
    return np.zeros((m,n))
def position_ships(ships_code,ships_size, m=10,n=10):
    """
    Returns a list of positions values in the form of letter and number 
    based on the ship sizes in dictionary ships_size
    """
    ships_pos_dic = {} #Dictionary holding position for each list

    pc_board = create_board()
    for iship,isize  in ships_size.items():
        ships_pos_dic[iship] = []
        flagOkposition=True
        while flagOkposition:
            positionx = random.choice(range(0,n))
            positiony = random.choice(range(0,m))
            angleship = random.choice(("v","h"))
            print(f"first poistion of ship x{positionx}, y{positiony} and lays {angleship}")
            if angleship == "v":
                if (positiony + isize) >=m :
                    print("try another starting position")
                else:
                    print(positiony + isize)
                    pc_board[positiony:(positiony+isize),positionx] = ships_code[iship]
                    for ipos in range(positiony,positiony+isize):
                        list_ship_pos = ships_pos_dic[iship] 
                        list_ship_pos.append(ascii_uppercase[ipos]+str(positionx+1))
                    flagOkposition = False
            else:
                if (positionx + isize) >=n or positiony >=m:
                    print("try another starting position")
                else:
                    print(positionx+isize)
                    pc_board[positiony,positionx:(positionx+isize)] = ships_code[iship]
                    for ipos in range(positionx,positionx+isize):
                        list_ship_pos = ships_pos_dic[iship] 
                        list_ship_pos.append(ascii_uppercase[positiony+1]+str(ipos+1))
                    flagOkposition = False
    print(pc_board)
    print(ships_pos_dic)
#    list_final_pos = []
#    for positionlist in ships_pos_dic.values():
#        list_final_pos.extend(positionlist)
    return pc_board,ships_pos_dic 


In [54]:
pc_board,ships_pos_dic = position_ships(ships_code, ships_size)

first poistion of ship x4, y5 and lays v
try another starting position
first poistion of ship x9, y6 and lays h
try another starting position
first poistion of ship x3, y4 and lays v
9
first poistion of ship x1, y0 and lays h
5
first poistion of ship x2, y3 and lays v
6
first poistion of ship x4, y7 and lays v
try another starting position
first poistion of ship x8, y4 and lays v
7
first poistion of ship x0, y3 and lays h
2
[[0. 2. 2. 2. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 1. 0. 0. 0. 0. 4. 0.]
 [0. 0. 3. 1. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'carrier': ['E4', 'F4', 'G4', 'H4', 'I4'], 'battleship': ['B2', 'B3', 'B4', 'B5'], 'cruiser': ['D3', 'E3', 'F3'], 'submarine': ['E9', 'F9', 'G9'], 'destroyer': ['E1', 'E2']}


['E4',
 'F4',
 'G4',
 'H4',
 'I4',
 'B2',
 'B3',
 'B4',
 'B5',
 'D3',
 'E3',
 'F3',
 'E9',
 'F9',
 'G9',
 'E1',
 'E2']

In [14]:
ascii_lowercase[1]


'b'